[package]
name = "defined"
version = "0.4.1"
edition = "2024"
description = "A simpler Option type to circumvent orphan rules in sea-orm."
license = "MIT OR Apache-2.0"
repository = "https://github.com/franklx/defined"
documentation = "https://docs.rs/defined/latest/defined/"

publish = ["elleci", "crates-io"]

[features]
default = ["schemars", "serde", "sea-query", "oasgen"]
oasgen = ["dep:oasgen"]
schemars = ["dep:schemars", "dep:serde_json"]
sea-query = ["dep:sea-query"]
serde = ["dep:serde"]
panic_immediate_abort = []

[dependencies]
oasgen = { version = "0.25", optional = true }
schemars = { version = "1", optional = true }
sea-query = { version = "0.32", optional = true }
serde_json = { version = "1", optional = true }
serde = { version = "1", optional = true }
